# -*- coding: utf-8 -*-
NAME = 'hebill'
VERSION = '1.0.0'
DESCRIPTION = 'Hebill\' python library'
LONG_DESCRIPTION = 'README.MD'
LONG_DESCRIPTION_TYPE = 'text/markdown'
URL = 'http://www.hebill.net/'
AUTHOR = 'He Bill'
AUTHOR_EMAIL = 'hebill@hebill.net'
AUTHOR_URL = 'http://www.hebill.net/'
